name: Build, Push Docker Image & Update Manifest

on:
  push:
    branches:
      - main  # Chạy khi có push lên branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Docker Image Tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/app:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/app:${{ env.IMAGE_TAG }}

      - name: Clone External Repo
        run: |
          git clone https://${{ secrets.REPO_PAT }}@github.com/${{ secrets.REPO_OWNER }}/${{ secrets.REPO_NAME }}.git Repo-config
          cd Repo-config
          git checkout main

      - name: Debug External Repo Files
        run: |
          cd Repo-config
          ls -la  # Liệt kê tất cả các file để kiểm tra deploy.yaml có tồn tại không

          
      - name: Update Repo Manifest
        run: |
          cd Repo-config
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/app:${{ env.IMAGE_TAG }}|g" deploy.yaml

      - name: Commit and Push Updated Manifest
        run: |
          git config --global user.email "txphan99@gmail.com"
          git config --global user.name "txphan99"
          git add deploy.yaml
          git commit -m "Update manifest to use image ${{ secrets.DOCKER_USERNAME }}/app:${{ env.IMAGE_TAG }}"
          git push origin main
