name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên branch "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Get Git Tag
        run: echo "IMAGE_TAG=$(git describe --tags --always || echo latest)" >> $GITHUB_ENV

      - name: Build Docker image with tag
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image with tag
        run: docker push $IMAGE_NAME:$IMAGE_TAG

